### ISSUE TITLE
Confusion regarding pre-trained model

### ISSUE THREAD

**Issue by aasharib** [fdbtrs/Self-restrained-Triplet-Loss#4]
Can you please tell that model weights given in [https://github.com/fdbtrs/Self-restrained-Triplet-Loss/tree/master/weights](https://github.com/fdbtrs/Self-restrained-Triplet-Loss/tree/master/weights) are the feature extractor weights or the weights of model proposed by you?

**Comment by fdbtrs** [comment]
the weights of EUM model
